GHA: fold config.log output in failed cross-builds
Turn off the echo'ing of command with `set +x` when displaying
`config.log`, otherwise it may scramble the output.

diff --git a/vendor/opam/seq/.github/workflows/build-cross.yml b/vendor/opam/seq/.github/workflows/build-cross.yml
--- a/vendor/opam/seq/.github/workflows/build-cross.yml
+++ b/vendor/opam/seq/.github/workflows/build-cross.yml
@@ -14,7 +14,7 @@ concurrency:
   cancel-in-progress: true
 
 env:
-  res: 0
+  failed: 0
   TESTDIR: >-
     C:\Бактріан🐫
   STR_UTF8: >-
@@ -50,8 +50,11 @@ jobs:
           set -x
           ./configure --disable-warn-error --disable-ocamldoc \
               --disable-ocamltest --disable-stdlib-manpages \
-              --disable-dependency-generation --prefix="$PREFIX" || res=$?
-          if ! [ "$res" = 0 ]; then cat config.log; exit "$res"; fi
+              --disable-dependency-generation --prefix="$PREFIX" || failed=$?
+          if ((failed)) ; then set +x
+            echo ; echo "::group::config.log content ($(wc -l config.log) lines)"
+            cat config.log ; echo '::endgroup::' ; exit $failed
+          fi
           make -j
           make install
           cd "$HOME"
@@ -88,8 +91,11 @@ jobs:
         run: |
           set -x
           ./configure --prefix="$HOME/cross" --target=x86_64-w64-mingw32 \
-              TARGET_LIBDIR="$TESTDIR" || res=$?
-          if ! [ "$res" = 0 ]; then cat config.log; exit "$res"; fi
+              TARGET_LIBDIR="$TESTDIR" || failed=$?
+          if ((failed)) ; then set +x
+            echo ; echo "::group::config.log content ($(wc -l config.log) lines)"
+            cat config.log ; echo '::endgroup::' ; exit $failed
+          fi
           # The OOM-killer may be triggered if the number of parallel
           # jobs isn't limited.
           make crossopt -j$(nproc)
@@ -159,8 +165,11 @@ jobs:
         run: |
           set -x
           ./configure --prefix="$HOME/cross" --target=aarch64-linux-gnu \
-              || res=$?
-          if ! [ "$res" = 0 ]; then cat config.log; exit "$res"; fi
+              || failed=$?
+          if ((failed)) ; then set +x
+            echo ; echo "::group::config.log content ($(wc -l config.log) lines)"
+            cat config.log ; echo '::endgroup::' ; exit $failed
+          fi
           make crossopt -j
           make installcross
       - name: Show opt.opt configuration
@@ -250,8 +259,11 @@ jobs:
               AR="$DIR/llvm-ar" \
               PARTIALLD="$DIR/ld -r" \
               RANLIB="$DIR/llvm-ranlib" \
-              STRIP="$DIR/llvm-strip" || res=$?
-          if ! [ "$res" = 0 ]; then cat config.log; exit "$res"; fi
+              STRIP="$DIR/llvm-strip" || failed=$?
+          if ((failed)) ; then set +x
+            echo ; echo "::group::config.log content ($(wc -l config.log) lines)"
+            cat config.log ; echo '::endgroup::' ; exit $failed
+          fi
           make crossopt -j
           make installcross
       - name: Show opt.opt configuration
